export interface MembershipSummariesPayload {
	list: MembershipSummary[]
}

export interface MembershipSummary {
	id: number,
	visitorId: number,
	membershipId: number,
	constituentImportId: string,
	constituentId: string,
	cardType: string,
	categoryId: string,
	offeringId: string,
	name: string,
	barcode: string,
	acmeBarcode: string,
	email: string,
	firstName: string,
	lastName: string,
	phoneNumber: string,
	streetAddress1: string,
	city: string,
	state: string,
	zipCode: string,
	country: string,
	primaryCard: boolean,
	program: string,
	category: string,
	membershipTypeId: number,
	externalMembershipId: string,
	membershipJoinedDate: string,
	membershipStartDate: string,
	membershipExpirationDate: string,
	membershipStanding: string,
	membershipCategory: string,
	cardholderAttributes: any[],
	acmeMembershipNumber: string,
	cardStartDate: string,
	cardExpirationDate: string,
	cardStanding: string,
	auxiliary: boolean,
	customerId: number,
}